services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=engsoft2
      - RABBITMQ_DEFAULT_PASS=engsoft2
    networks:
      - membership-network
  cadastramento:
    build: cadastramento
    image: cadastramento
    ports:
      - "8000:8000"
    networks:
      - membership-network
    depends_on:
      - name-server
      - rabbitmq
    environment:
      - eureka.client.serviceUrl.defaultZone=http://name-server:8761/eureka
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.port=5672
      - spring.rabbitmq.username=engsoft2
      - spring.rabbitmq.password=engsoft2
  pagamentos:
    build: pagamentos
    image: pagamentos
    ports:
      - "8100:8100"
    networks:
      - membership-network
    depends_on:
      - name-server
      - rabbitmq
    environment:
      - eureka.client.serviceUrl.defaultZone=http://name-server:8761/eureka
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.port=5672
      - spring.rabbitmq.username=engsoft2
      - spring.rabbitmq.password=engsoft2
  api-gateway:
    build: api-gateway
    image: gateway
    ports:
      - "8765:8765"
    networks:
      - membership-network
    depends_on:
      - name-server
    environment:
      - eureka.client.serviceUrl.defaultZone=http://name-server:8761/eureka
  name-server:
    build: name-server
    image: nameserver
    ports:
      - "8761:8761"
    networks:
      - membership-network
  assinaturas-validas:
    build: assinaturas-validas
    image: assinaturas
    ports:
      - "8150:8150"
    networks:
      - membership-network
    depends_on:
      - name-server
      - rabbitmq
    environment:
      - eureka.client.serviceUrl.defaultZone=http://name-server:8761/eureka
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.port=5672
      - spring.rabbitmq.username=engsoft2
      - spring.rabbitmq.password=engsoft2
networks:
  membership-network:

